theme: jekyll-theme-cayman

# 使用URL设置图标
favicon: https://s1.4sai.com/src/img/png/2c/2c4fa0389cad420c85e873c092dd5163.png?imageMogr2/auto-orient/thumbnail/!132x132r/gravity/Center/crop/132x132/quality/85/&e=1735488000&token=1srnZGLKZ0Aqlz6dk7yF4SkiYf4eP-YrEOdM1sob:5CD3hSucTKWV92X3Z5tukk0ucb4=
